"use client";
import { useState } from "react";

const tools = ["LIVE BROWSER", "SCREENSHOT + DIFF", "DEVTOOLS TELEMETRY", "AXE + LIGHTHOUSE", "SPACING + GRID", "CONTRAST + TARGETS"];

export default function Home() {
  const [copied, setCopied] = useState(false);
  async function copy() { await navigator.clipboard?.writeText("npm install --global @forma-ai/forma"); setCopied(true); setTimeout(() => setCopied(false), 1600); }
  return <main>
    <nav className="nav shell"><a className="brand" href="#top"><span className="brand-mark">F</span> FORMA<span className="beta">FIELD TEST / 01</span></a><div className="nav-links"><a href="#how">How it works</a><a href="#toolbox">Toolbox</a><a href="https://github.com/EgoisticCoder/Forma">GitHub ↗</a></div><a className="nav-cta" href="#install">GET IN THE LOOP <span>↗</span></a></nav>
    <section id="top" className="hero shell">
      <div className="hero-kicker"><span className="pulse"/> OPEN SOURCE · LOCAL-FIRST WORKFLOW · YOUR MODEL, YOUR CALL</div>
      <div className="hero-grid"><div><h1>Your code<br/>can <em>see</em> the page<br/>now<span className="period">.</span></h1><p className="hero-copy">FORMA gives your coding agent eyes, a browser, and a UI/UX specialist. It spots what the DOM can’t explain, then helps your coding model fix what it finds.</p><div className="hero-actions"><a href="#install" className="button button-light">INSTALL FORMA <span>↓</span></a><a href="#how" className="text-link">SEE HOW IT WORKS <span>↘</span></a></div><div className="hero-footnote"><span className="crosshair">⌖</span> Made for developers and vibe coders who want to ship interfaces that feel right.</div></div>
      <div className="terminal-wrap"><div className="terminal-label"><span>LIVE AUDIT / WEB.APP</span><span>390 × 854 <i>●</i></span></div><div className="browser-card"><div className="browser-chrome"><span/><span/><span/><div>localhost:3000 / checkout</div><b>•••</b></div><div className="mock-page"><div className="mock-nav"><strong>MONO<span>FORM</span></strong><span>SHOP&nbsp;&nbsp; JOURNAL&nbsp;&nbsp; BAG (2)</span></div><div className="mock-hero"><div className="mock-stamp">OBJECT<br/>NO. 04</div><h3>Less stuff.<br/><i>More feeling.</i></h3><p>Thoughtful everyday objects, made to stay.</p><div className="mock-button">DISCOVER THE COLLECTION ↗</div><div className="mock-orb"/></div><div className="mock-status"><span>01 — VISUAL HIERARCHY</span><span>02 — TOUCH TARGETS</span><span>03 — COLOR CONTRAST</span></div></div></div><div className="audit-callout"><div className="callout-top"><span><i className="pulse"/> FORMA VISION AUDIT</span><span>3 SIGNALS</span></div><div className="callout-row"><b>01</b><span>Primary action gets lost against the hero.</span><small>HIERARCHY</small></div><div className="callout-row"><b>02</b><span>Mobile nav links fall below 44px.</span><small>TOUCH</small></div><div className="callout-row"><b>03</b><span>Body copy is 12px at 390px viewport.</span><small>TYPE</small></div><div className="callout-bottom">AGENT: FIXING 3 ISSUES <span className="scanline"/></div></div><div className="side-index">VISUAL DEBUGGING SYSTEM <span>→</span> 001—∞</div></div></div>
      <div className="hero-ticker"><span>SCREENSHOT</span><b>×</b><span>MEASURED CONTEXT</span><b>×</b><span>MODEL JUDGEMENT</span><b>×</b><span>CODE CHANGE</span><b>×</b><span>VISUAL PROOF</span><b>×</b><span>SCREENSHOT</span></div>
    </section>
    <section className="manifesto shell" id="how"><div className="section-tag">// 001 — THE LOOP</div><div className="manifesto-content"><h2>Not another<br/>code autocomplete.</h2><p>Most coding agents are good at changing code. FORMA adds the missing feedback loop: open the real page, collect browser facts, ask a vision model what feels off, let your coding model make the change, and compare the result.</p><div className="steps"><div><b>01 / LOOK</b><span>Open your page at desktop, tablet, mobile.</span></div><div><b>02 / MEASURE</b><span>Capture pixels, DOM, console, network, accessibility.</span></div><div><b>03 / REASON</b><span>FORMA audits the screenshot with measured context.</span></div><div><b>04 / FIX</b><span>Your coding model edits. FORMA checks the delta.</span></div></div></div></section>
    <section className="toolbox-section" id="toolbox"><div className="shell"><div className="section-tag">// 002 — THE BROWSER TOOLBOX</div><div className="toolbox-head"><h2>See the details.<br/><i>Ship the fix.</i></h2><p>One MCP server. Every MCP-compatible coding agent and IDE can plug in. Keep your editor; give it a browser.</p></div><div className="tool-grid">{tools.map((t,i)=><div className="tool-card" key={t}><span className="tool-number">0{i+1}</span><div className={`tool-icon icon-${i}`}><span>{["◉","▧","⌁","◈","⊞","◍"][i]}</span></div><b>{t}</b><p>{["Responsive page capture across real viewports.","Before/after visual change map.","Console, crashes, requests, fonts, overflow, targets.","Accessibility violations and performance signals.","Sibling gaps, padding, section rhythm, 8px grid.","WCAG text contrast and undersized controls."][i]}</p></div>)}</div><div className="mcp-note"><div className="mcp-glyph">M<br/>C<br/>P</div><p><b>Bring your own agent.</b> OpenCode, Claude Code, Cursor, Windsurf, VS Code, or any MCP host. FORMA’s browser tools stay portable.</p><a href="https://github.com/EgoisticCoder/Forma/tree/main/packages/forma-mcp">MCP SETUP <span>↗</span></a></div></div></section>
    <section className="split shell"><div className="section-tag">// 003 — TWO MODELS. TWO JOBS.</div><div className="split-grid"><div><div className="model-stamp">VLM / THE EYE</div><h2>FORMA sees<br/>the interface.</h2><p>A fine-tuned Qwen2.5-VL adapter trained for single-turn UI/UX audits. It reads the screenshot and measured browser context, then returns a structured report.</p><div className="model-rule"><span>NO TOOL CALLING</span><span>NO CODE EDITING</span><span>ONE JOB: AUDIT</span></div></div><div><div className="model-stamp">LLM / THE HAND</div><h2>Your coding model<br/>makes the change.</h2><p>Choose an OpenAI-compatible provider or local Ollama model. It gets the normal coding workflow—files, shell, search, plans—plus the browser tools.</p><div className="model-rule"><span>YOU PICK PROVIDER</span><span>ASK BEFORE ACTIONS</span><span>YOU STAY IN CONTROL</span></div></div></div><div className="flowbar"><span>SCREENSHOT + TELEMETRY</span><b>→</b><span>FORMA AUDIT</span><b>→</b><span>CODE EDIT</span><b>→</b><span>VISUAL DIFF</span><b>↻</b></div></section>
    <section className="install-section" id="install"><div className="shell install-grid"><div><div className="section-tag">// 004 — BOOT SEQUENCE</div><h2>From zero<br/>to <i>eyes open.</i></h2><p>Start the FORMA model in your Kaggle notebook, install the CLI, then connect your endpoint and coding model. Your tunnel URL changes when the notebook restarts.</p><button className="button button-light" onClick={copy}>{copied ? "COPIED ✓" : "COPY NPM INSTALL"} <span>⎘</span></button><div className="install-command"><span>$</span> npm install --global @forma-ai/forma</div></div><div className="install-steps"><div><strong>01</strong><div><b>START THE MODEL</b><p>Run the single-cell Kaggle server. Copy the URL and bearer token printed at startup.</p></div></div><div><strong>02</strong><div><b>INSTALL THE AGENT</b><p>Install Forma with npm. Chromium is downloaded on first browser use.</p></div></div><div><strong>03</strong><div><b>CONNECT YOUR MODELS</b><p>Paste the Kaggle endpoint and token. Choose your coding model provider.</p></div></div><div><strong>04</strong><div><b>ASK FOR THE FIX</b><p>Run <code>forma audit https://your-site.dev</code>, or enter a workspace and describe what to build.</p></div></div></div></div></section>
    <section className="final shell"><div className="section-tag">// READY WHEN YOU ARE</div><h2>Make the loop<br/><i>visible.</i></h2><p>Bring your local page. Bring the model you trust to write code. Let FORMA tell you what the screenshot sees.</p><div className="final-actions"><a href="https://github.com/EgoisticCoder/Forma" className="button button-dark">EXPLORE THE REPO ↗</a><a href="https://github.com/EgoisticCoder/Forma#quickstart" className="text-link dark-link">READ THE QUICKSTART →</a></div><div className="final-coordinates">FORMA / VISUAL UI DEBUGGING<br/>OPEN SOURCE TOOLING · EARLY BUILD<br/>NO ACCOUNTS. NO PRODUCT TELEMETRY.</div></section>
    <footer className="footer shell"><a className="brand" href="#top"><span className="brand-mark">F</span> FORMA</a><span>SEE WHAT YOUR CODE SHIPS.</span><div><a href="https://github.com/EgoisticCoder/Forma">GITHUB ↗</a><a href="#install">INSTALL ↗</a></div><small>© 2026 FORMA — Built to make interfaces better, one feedback loop at a time.</small></footer>
  </main>;
}
